"""
Create a Jupyter notebook from the analysis script source code.
Splits code into logical cells with markdown headers.
"""
import json
import uuid

def make_cell(cell_type, source_lines):
    """Create a notebook cell."""
    # Ensure each line (except last) ends with \n
    formatted = []
    for i, line in enumerate(source_lines):
        if i < len(source_lines) - 1:
            formatted.append(line + '\n' if not line.endswith('\n') else line)
        else:
            formatted.append(line.rstrip('\n'))
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": formatted,
        **({"execution_count": None, "outputs": []} if cell_type == "code" else {}),
        "id": str(uuid.uuid4())[:8]
    }

def md(text):
    return make_cell("markdown", text.split('\n'))

def code(text):
    return make_cell("code", text.split('\n'))

cells = []

# Title
cells.append(md("# Chicago Traffic Crash Analysis (2016\u20132023)\n## Data-Driven Insights for Road Safety\n\n**Tools**: pandas, SQLite, scipy, statsmodels, scikit-learn, folium, matplotlib, seaborn, python-pptx\n\n---"))

# Phase 0
cells.append(md("## Phase 0: Environment & Library Verification"))
cells.append(code(
'import warnings\n'
'warnings.filterwarnings(\'ignore\')\n'
'\n'
'import pandas as pd\n'
'import numpy as np\n'
'import matplotlib\n'
'matplotlib.use(\'Agg\')\n'
'import matplotlib.pyplot as plt\n'
'import seaborn as sns\n'
'import scipy\n'
'import scipy.stats as stats\n'
'import statsmodels.api as sm\n'
'import statsmodels.formula.api as smf\n'
'from statsmodels.tsa.seasonal import seasonal_decompose\n'
'from sklearn.cluster import DBSCAN\n'
'import folium\n'
'from folium.plugins import HeatMap, MiniMap, Fullscreen, MousePosition\n'
'import sqlite3\n'
'import calendar\n'
'import os\n'
'from pptx import Presentation\n'
'from pptx.util import Inches, Pt, Emu\n'
'from pptx.dml.color import RGBColor\n'
'from pptx.enum.text import PP_ALIGN\n'
'from pptx.enum.shapes import MSO_SHAPE\n'
'\n'
'import matplotlib.ticker as ticker\n'
'\n'
'sns.set_theme(style=\'whitegrid\')\n'
'plt.rcParams.update({\n'
'    \'figure.dpi\': 250, \'savefig.dpi\': 250,\n'
'    \'figure.facecolor\': \'white\', \'savefig.facecolor\': \'white\',\n'
'    \'font.family\': \'sans-serif\',\n'
'    \'font.size\': 11, \'axes.titlesize\': 14, \'axes.labelsize\': 12,\n'
'})\n'
'\n'
'OUTPUT_DIR = \'output\'\n'
'os.makedirs(OUTPUT_DIR, exist_ok=True)\n'
'\n'
'print("All libraries loaded successfully.")\n'
'print(f"pandas {pd.__version__}, numpy {np.__version__}, scipy {scipy.__version__}")\n'
'print(f"matplotlib {matplotlib.__version__}, seaborn {sns.__version__}")\n'
'print(f"statsmodels {sm.__version__}")'
))

# Phase 1
cells.append(md("---\n## Phase 1: Data Loading, Cleaning & Feature Engineering"))
cells.append(md("### 1.1 Load CSV"))
cells.append(code(
'df_raw = pd.read_csv(\'Traffic_Crashes.csv\', parse_dates=[\'CRASH_DATE\'], low_memory=False)\n'
'print(f"Raw dataset: {df_raw.shape[0]:,} rows, {df_raw.shape[1]} columns")\n'
'print(f"Date range: {df_raw[\'CRASH_DATE\'].min()} to {df_raw[\'CRASH_DATE\'].max()}")\n'
'print(f"\\nColumn dtypes:\\n{df_raw.dtypes.to_string()}")'
))

cells.append(md("### 1.2 Data Quality Validation"))
cells.append(code(
'null_counts = df_raw.isnull().sum()\n'
'null_pct = (null_counts / len(df_raw) * 100).round(1)\n'
'null_summary = pd.DataFrame({\'Missing\': null_counts, \'% Missing\': null_pct})\n'
'null_summary = null_summary[null_summary[\'Missing\'] > 0].sort_values(\'% Missing\', ascending=False)\n'
'print("Columns with missing values:")\n'
'print(null_summary.to_string())\n'
'print(f"\\nCRASH_HOUR range: {df_raw[\'CRASH_HOUR\'].min()} - {df_raw[\'CRASH_HOUR\'].max()}")\n'
'print(f"CRASH_DAY_OF_WEEK range: {df_raw[\'CRASH_DAY_OF_WEEK\'].min()} - {df_raw[\'CRASH_DAY_OF_WEEK\'].max()}")\n'
'print(f"\\nHIT_AND_RUN_I value counts:")\n'
'print(df_raw[\'HIT_AND_RUN_I\'].value_counts(dropna=False).to_string())'
))

cells.append(md("### 1.3 Filter & Clean"))
cells.append(code(
'df = df_raw.copy()\n'
'df[\'CRASH_YEAR\'] = df[\'CRASH_DATE\'].dt.year\n'
'print(f"Year distribution before filter:")\n'
'print(df[\'CRASH_YEAR\'].value_counts().sort_index().to_string())\n'
'\n'
'df = df[df[\'CRASH_YEAR\'].between(2016, 2023)].copy()\n'
'print(f"\\nAfter filtering to 2016-2023: {len(df):,} rows")\n'
'\n'
'df = df.drop(columns=[\'DOORING_I\', \'LANE_CNT\'], errors=\'ignore\')\n'
'print("Dropped DOORING_I (99.7% blank) and LANE_CNT (74.7% missing)")\n'
'\n'
'df[\'HIT_AND_RUN_I\'] = df[\'HIT_AND_RUN_I\'].fillna(\'N\')\n'
'print(f"\\nHIT_AND_RUN_I after cleaning:")\n'
'print(df[\'HIT_AND_RUN_I\'].value_counts().to_string())\n'
'\n'
'before = len(df)\n'
'df = df.dropna(subset=[\'CRASH_HOUR\', \'CRASH_DAY_OF_WEEK\'])\n'
'print(f"\\nDropped {before - len(df)} rows with null CRASH_HOUR/CRASH_DAY_OF_WEEK")\n'
'print(f"Final cleaned dataset: {len(df):,} rows")'
))

cells.append(md("### 1.4 Feature Engineering"))
cells.append(code(
'wet_weather = [\'RAIN\', \'SNOW\', \'FREEZING RAIN/DRIZZLE\', \'SLEET/HAIL\', \'BLOWING SNOW\']\n'
'wet_surface = [\'WET\', \'SNOW OR SLUSH\', \'ICE\']\n'
'df[\'IS_WET_WEATHER\'] = df[\'WEATHER_CONDITION\'].isin(wet_weather).astype(int)\n'
'df[\'IS_WET_SURFACE\'] = df[\'ROADWAY_SURFACE_COND\'].isin(wet_surface).astype(int)\n'
'df[\'HAS_INJURY\'] = (df[\'INJURIES_TOTAL\'] > 0).astype(int)\n'
'df[\'HAS_FATAL\'] = (df[\'INJURIES_FATAL\'] > 0).astype(int)\n'
'df[\'IS_SEVERE\'] = df[\'MOST_SEVERE_INJURY\'].isin([\'INCAPACITATING INJURY\', \'FATAL\']).astype(int)\n'
'df[\'IS_WEEKEND\'] = df[\'CRASH_DAY_OF_WEEK\'].isin([1, 7]).astype(int)\n'
'\n'
'def assign_time_period(hour):\n'
'    if 6 <= hour <= 9: return \'Morning Rush\'\n'
'    elif 10 <= hour <= 15: return \'Midday\'\n'
'    elif 16 <= hour <= 19: return \'Evening Rush\'\n'
'    elif 20 <= hour <= 23: return \'Night\'\n'
'    else: return \'Late Night\'\n'
'\n'
'df[\'TIME_PERIOD\'] = df[\'CRASH_HOUR\'].apply(assign_time_period)\n'
'\n'
'day_map = {1: \'Sunday\', 2: \'Monday\', 3: \'Tuesday\', 4: \'Wednesday\',\n'
'           5: \'Thursday\', 6: \'Friday\', 7: \'Saturday\'}\n'
'df[\'DAY_NAME\'] = df[\'CRASH_DAY_OF_WEEK\'].map(day_map)\n'
'df[\'MONTH_NAME\'] = df[\'CRASH_MONTH\'].apply(lambda m: calendar.month_abbr[int(m)])\n'
'\n'
'def speed_cat(s):\n'
'    if pd.isna(s): return \'Unknown\'\n'
'    if s <= 20: return \'0-20 mph\'\n'
'    if s <= 30: return \'25-30 mph\'\n'
'    if s <= 40: return \'35-40 mph\'\n'
'    return \'45+ mph\'\n'
'\n'
'df[\'SPEED_CATEGORY\'] = df[\'POSTED_SPEED_LIMIT\'].apply(speed_cat)\n'
'df[\'DAMAGE_LEVEL\'] = df[\'DAMAGE\'].map({\'$500 OR LESS\': 1, \'$501 - $1,500\': 2, \'OVER $1,500\': 3})\n'
'df[\'IS_DARK\'] = df[\'LIGHTING_CONDITION\'].str.contains(\'DARK\', na=False).astype(int)\n'
'\n'
'print("Feature engineering complete.")\n'
'for col in [\'IS_WET_WEATHER\', \'IS_WET_SURFACE\', \'HAS_INJURY\', \'HAS_FATAL\', \'IS_SEVERE\', \'IS_WEEKEND\', \'IS_DARK\']:\n'
'    print(f"  {col}: {df[col].sum():,} ({df[col].mean()*100:.1f}%)")'
))

cells.append(md("### 1.5 Save Cleaned Data"))
cells.append(code(
'try:\n'
'    df.to_parquet(\'crashes_clean.parquet\', index=False)\n'
'    print("Saved to crashes_clean.parquet")\n'
'except Exception as e:\n'
'    print(f"Parquet save failed ({e}), falling back to CSV")\n'
'    df.to_csv(\'crashes_clean.csv\', index=False)'
))

# Phase 2: SQL
cells.append(md("---\n## Phase 2: SQL-Based Exploration (SQLite)\n\nDemonstrating SQL proficiency alongside Python for data exploration."))
cells.append(code(
'conn = sqlite3.connect(\'crashes.db\')\n'
'df.to_sql(\'crashes\', conn, if_exists=\'replace\', index=False)\n'
'print(f"Loaded {len(df):,} rows into SQLite database")'
))

cells.append(md("### Query 1: Crashes by Year"))
cells.append(code(
'q1 = """\n'
'SELECT CRASH_YEAR, COUNT(*) as total_crashes,\n'
'       SUM(INJURIES_TOTAL) as total_injuries,\n'
'       SUM(INJURIES_FATAL) as total_fatalities,\n'
'       ROUND(AVG(HAS_INJURY)*100, 1) as injury_rate_pct,\n'
'       ROUND(AVG(HAS_FATAL)*100, 3) as fatality_rate_pct\n'
'FROM crashes GROUP BY CRASH_YEAR ORDER BY CRASH_YEAR\n'
'"""\n'
'print(pd.read_sql_query(q1, conn).to_string(index=False))'
))

cells.append(md("### Query 2: Day-of-Week \u00d7 Hour Cross-Tab"))
cells.append(code(
'q2 = """\n'
'SELECT DAY_NAME, CRASH_DAY_OF_WEEK, CRASH_HOUR, COUNT(*) as crash_count\n'
'FROM crashes GROUP BY CRASH_DAY_OF_WEEK, CRASH_HOUR\n'
'ORDER BY CRASH_DAY_OF_WEEK, CRASH_HOUR\n'
'"""\n'
'result2 = pd.read_sql_query(q2, conn)\n'
'heatmap_data = result2.pivot(index=\'DAY_NAME\', columns=\'CRASH_HOUR\', values=\'crash_count\')\n'
'day_order = [\'Monday\', \'Tuesday\', \'Wednesday\', \'Thursday\', \'Friday\', \'Saturday\', \'Sunday\']\n'
'heatmap_data = heatmap_data.reindex(day_order)\n'
'print("Day x Hour cross-tab generated for heatmap.")\n'
'print(heatmap_data.iloc[:, :8].to_string())'
))

cells.append(md("### Query 3: Weather Condition Impact"))
cells.append(code(
'q3 = """\n'
'SELECT WEATHER_CONDITION, COUNT(*) as total_crashes,\n'
'       SUM(HAS_INJURY) as injury_crashes,\n'
'       ROUND(AVG(HAS_INJURY)*100, 1) as injury_rate_pct,\n'
'       SUM(INJURIES_FATAL) as fatalities\n'
'FROM crashes WHERE WEATHER_CONDITION IS NOT NULL AND WEATHER_CONDITION != \'UNKNOWN\'\n'
'GROUP BY WEATHER_CONDITION ORDER BY total_crashes DESC\n'
'"""\n'
'print(pd.read_sql_query(q3, conn).to_string(index=False))'
))

cells.append(md("### Query 4: Top 15 Contributory Causes"))
cells.append(code(
'q4 = """\n'
'SELECT PRIM_CONTRIBUTORY_CAUSE, COUNT(*) as total_crashes,\n'
'       SUM(HAS_INJURY) as injury_crashes,\n'
'       ROUND(AVG(HAS_INJURY)*100, 1) as injury_rate_pct,\n'
'       SUM(INJURIES_FATAL) as fatalities\n'
'FROM crashes WHERE PRIM_CONTRIBUTORY_CAUSE NOT IN (\'UNABLE TO DETERMINE\', \'NOT APPLICABLE\')\n'
'GROUP BY PRIM_CONTRIBUTORY_CAUSE ORDER BY total_crashes DESC LIMIT 15\n'
'"""\n'
'print(pd.read_sql_query(q4, conn).to_string(index=False))'
))

cells.append(md("### Query 5: Hit-and-Run Overview"))
cells.append(code(
'q5 = """\n'
'SELECT HIT_AND_RUN_I, COUNT(*) as total_crashes,\n'
'       SUM(HAS_INJURY) as injury_crashes,\n'
'       ROUND(AVG(HAS_INJURY)*100, 1) as injury_rate_pct,\n'
'       ROUND(AVG(INJURIES_TOTAL), 3) as avg_injuries_per_crash,\n'
'       SUM(INJURIES_FATAL) as fatalities\n'
'FROM crashes GROUP BY HIT_AND_RUN_I\n'
'"""\n'
'print(pd.read_sql_query(q5, conn).to_string(index=False))'
))

cells.append(md("### Query 6: Top 20 Streets by Crash Volume"))
cells.append(code(
'q6 = """\n'
'SELECT STREET_NAME, COUNT(*) as total_crashes,\n'
'       SUM(HAS_INJURY) as injury_crashes,\n'
'       SUM(INJURIES_FATAL) as fatalities,\n'
'       ROUND(AVG(HAS_INJURY)*100, 1) as injury_rate_pct\n'
'FROM crashes WHERE STREET_NAME IS NOT NULL\n'
'GROUP BY STREET_NAME ORDER BY total_crashes DESC LIMIT 20\n'
'"""\n'
'print(pd.read_sql_query(q6, conn).to_string(index=False))'
))

# Phase 3a: Temporal
cells.append(md("---\n## Phase 3: Statistical Analysis\n### 3a: Temporal Correlation Analysis\n**Q1: Is there a correlation between time of year/week/day and crashes?**"))
cells.append(code(
'# Monthly chi-squared\n'
'monthly_counts = df.groupby(\'CRASH_MONTH\').size()\n'
'expected_monthly = np.full(12, len(df) / 12)\n'
'chi2_month, p_month = stats.chisquare(monthly_counts.values, expected_monthly)\n'
'print(f"1. Monthly Chi-squared: chi2={chi2_month:,.1f}, p={p_month:.2e}")\n'
'\n'
'# Day-of-week chi-squared\n'
'dow_counts = df.groupby(\'CRASH_DAY_OF_WEEK\').size()\n'
'expected_dow = np.full(7, len(df) / 7)\n'
'chi2_dow, p_dow = stats.chisquare(dow_counts.values, expected_dow)\n'
'print(f"2. Day-of-Week Chi-squared: chi2={chi2_dow:,.1f}, p={p_dow:.2e}")\n'
'\n'
'# Hourly chi-squared\n'
'hourly_counts = df.groupby(\'CRASH_HOUR\').size()\n'
'expected_hourly = np.full(24, len(df) / 24)\n'
'chi2_hour, p_hour = stats.chisquare(hourly_counts.values, expected_hourly)\n'
'print(f"3. Hourly Chi-squared: chi2={chi2_hour:,.1f}, p={p_hour:.2e}")\n'
'\n'
'# Weekend vs weekday (Mann-Whitney U)\n'
'df[\'CRASH_DATE_ONLY\'] = df[\'CRASH_DATE\'].dt.date\n'
'daily_counts = df.groupby([\'CRASH_DATE_ONLY\', \'IS_WEEKEND\']).size().reset_index(name=\'count\')\n'
'weekday_daily = daily_counts[daily_counts[\'IS_WEEKEND\'] == 0][\'count\']\n'
'weekend_daily = daily_counts[daily_counts[\'IS_WEEKEND\'] == 1][\'count\']\n'
'u_stat, p_mw = stats.mannwhitneyu(weekday_daily, weekend_daily, alternative=\'two-sided\')\n'
'print(f"4. Weekend vs Weekday: U={u_stat:,.0f}, p={p_mw:.2e}")\n'
'print(f"   Weekday mean: {weekday_daily.mean():.1f}, Weekend mean: {weekend_daily.mean():.1f}")\n'
'\n'
'# Year-over-year Pearson\n'
'yearly_counts = df.groupby(\'CRASH_YEAR\').size()\n'
'r_year, p_year = stats.pearsonr(yearly_counts.index, yearly_counts.values)\n'
'print(f"5. Year-over-Year: r={r_year:.3f}, p={p_year:.4f}")\n'
'\n'
'peak_month = monthly_counts.idxmax()\n'
'peak_day = dow_counts.idxmax()\n'
'peak_hour = hourly_counts.idxmax()\n'
'print(f"\\nPeak month: {calendar.month_name[peak_month]}, Peak day: {day_map[peak_day]}, Peak hour: {int(peak_hour):02d}:00")'
))

cells.append(md("### Monthly Crash Counts & Seasonal Pattern\n\nTop panel: monthly crash timeline 2016\u20132023 (note COVID-19 dip). Bottom panel: which month has the most crashes on average?"))
cells.append(code(
'import matplotlib.dates as mdates\n'
'\n'
'monthly_ts = df.groupby([df[\'CRASH_DATE\'].dt.to_period(\'M\')]).size()\n'
'monthly_ts.index = monthly_ts.index.to_timestamp()\n'
'monthly_ts = monthly_ts.sort_index()\n'
'full_range = pd.date_range(monthly_ts.index.min(), monthly_ts.index.max(), freq=\'MS\')\n'
'monthly_ts = monthly_ts.reindex(full_range, fill_value=0)\n'
'decomp = seasonal_decompose(monthly_ts, model=\'additive\', period=12)\n'
'covid_date = pd.Timestamp(\'2020-03-15\')\n'
'\n'
'fig, (ax_top, ax_bot) = plt.subplots(2, 1, figsize=(14, 9), gridspec_kw={\'height_ratios\': [1.3, 1]})\n'
'fig.patch.set_linewidth(0)\n'
'\n'
'# Top panel: monthly bar chart\n'
'month_year = df.groupby([df[\'CRASH_DATE\'].dt.to_period(\'M\')]).size()\n'
'month_year.index = month_year.index.to_timestamp()\n'
'month_year = month_year.sort_index()\n'
'full_range_bar = pd.date_range(month_year.index.min(), month_year.index.max(), freq=\'MS\')\n'
'month_year = month_year.reindex(full_range_bar, fill_value=0)\n'
'ax_top.bar(month_year.index, month_year.values, width=25, color=\'#005B96\', alpha=0.85, edgecolor=\'none\')\n'
'ax_top.set_title(\'Monthly Crash Counts \\u2014 Timeline (2016\\u20132023)\', fontsize=15, fontweight=\'bold\', pad=12)\n'
'ax_top.set_ylabel(\'Crashes per Month\', fontsize=11)\n'
'ax_top.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\'{x:,.0f}\'))\n'
'ax_top.yaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'ax_top.xaxis.grid(False)\n'
'ax_top.axvspan(pd.Timestamp(\'2020-03-01\'), pd.Timestamp(\'2020-06-01\'), alpha=0.15, color=\'red\', zorder=0)\n'
'ax_top.annotate(\'COVID-19\\nLockdown\', xy=(covid_date, month_year.min()),\n'
'                xytext=(pd.Timestamp(\'2020-08-01\'), month_year.max() * 0.8),\n'
'                fontsize=10, color=\'red\', fontweight=\'bold\',\n'
'                arrowprops=dict(arrowstyle=\'->\', color=\'red\', lw=1.5))\n'
'ax_top.xaxis.set_major_locator(mdates.YearLocator())\n'
'ax_top.xaxis.set_major_formatter(mdates.DateFormatter(\'%Y\'))\n'
'\n'
'# Bottom panel: average by calendar month\n'
'avg_by_month = df.groupby(df[\'CRASH_DATE\'].dt.month).size() / df[\'CRASH_YEAR\'].nunique()\n'
'month_names = [calendar.month_abbr[m] for m in avg_by_month.index]\n'
'bar_colors_avg = [\'#E63946\' if m == peak_month else \'#457B9D\' for m in avg_by_month.index]\n'
'bars_avg = ax_bot.bar(month_names, avg_by_month.values, color=bar_colors_avg, alpha=0.85, edgecolor=\'white\')\n'
'for bar, val in zip(bars_avg, avg_by_month.values):\n'
'    ax_bot.text(bar.get_x() + bar.get_width()/2, val + 100,\n'
'                f\'{val:,.0f}\', ha=\'center\', va=\'bottom\', fontsize=8, fontweight=\'bold\')\n'
'ax_bot.set_title(\'Which Month Has the Most Crashes? (8-Year Average)\', fontsize=13, fontweight=\'bold\', pad=10)\n'
'ax_bot.set_ylabel(\'Avg Crashes / Month\', fontsize=11)\n'
'ax_bot.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\'{x:,.0f}\'))\n'
'ax_bot.yaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'ax_bot.xaxis.grid(False)\n'
'trough_month = avg_by_month.idxmin()\n'
'ax_bot.annotate(f\'Peak: {calendar.month_name[peak_month]}\\n(avg {avg_by_month[peak_month]:,.0f}/month)\',\n'
'                xy=(peak_month - 1, avg_by_month[peak_month]),\n'
'                xytext=(peak_month + 1.5, avg_by_month[peak_month] * 1.08),\n'
'                fontsize=10, color=\'#E63946\', fontweight=\'bold\',\n'
'                arrowprops=dict(arrowstyle=\'->\', color=\'#E63946\', lw=1.5))\n'
'ax_bot.annotate(f\'Low: {calendar.month_name[trough_month]}\',\n'
'                xy=(trough_month - 1, avg_by_month[trough_month]),\n'
'                xytext=(trough_month - 2.5, avg_by_month[trough_month] * 0.85),\n'
'                fontsize=9, color=\'#457B9D\', fontweight=\'bold\',\n'
'                arrowprops=dict(arrowstyle=\'->\', color=\'#457B9D\', lw=1))\n'
'fig.text(0.5, -0.01,\n'
'         f\'Top: crash timeline showing COVID-19 dip in 2020. \'\n'
'         f\'Bottom: {calendar.month_name[peak_month]} averages {avg_by_month[peak_month]:,.0f} crashes/month \'\n'
'         f\'vs {calendar.month_name[trough_month]} at {avg_by_month[trough_month]:,.0f} (8-year average).\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'plt.tight_layout(rect=[0, 0.03, 1, 1])\n'
'plt.subplots_adjust(hspace=0.35)\n'
'plt.savefig(f\'{OUTPUT_DIR}/01_time_series_decomposition.png\', bbox_inches=\'tight\')\n'
'plt.show()\n'
'print("Saved: 01_time_series_decomposition.png")'
))

# Phase 3b: Wet Weather
cells.append(md("---\n### 3b: Wet Weather & Crash Analysis\n**Q2: Is there a causal relationship between wet weather conditions and crashes?**"))

cells.append(md("#### Level 1: Naive Count Comparison"))
cells.append(code(
'print("LEVEL 1: NAIVE COUNT COMPARISON")\n'
'wet_inj_rate = df[df[\'IS_WET_WEATHER\']==1][\'HAS_INJURY\'].mean()\n'
'dry_inj_rate = df[df[\'IS_WET_WEATHER\']==0][\'HAS_INJURY\'].mean()\n'
'print(f"Injury rate in wet weather: {wet_inj_rate*100:.1f}%")\n'
'print(f"Injury rate in dry weather: {dry_inj_rate*100:.1f}%")\n'
'print(f"Difference: {(wet_inj_rate - dry_inj_rate)*100:.1f} percentage points")'
))

cells.append(md("#### Level 2: Exposure-Adjusted Crash Rates"))
cells.append(code(
'print("LEVEL 2: EXPOSURE-ADJUSTED CRASH RATES")\n'
'pct_wet_crashes = df[\'IS_WET_WEATHER\'].mean() * 100\n'
'pct_dry_crashes = 100 - pct_wet_crashes\n'
'pct_wet_days = 34.0  # NOAA\n'
'pct_dry_days = 66.0\n'
'cri_wet = pct_wet_crashes / pct_wet_days\n'
'cri_dry = pct_dry_crashes / pct_dry_days\n'
'print(f"Wet weather: {pct_wet_crashes:.1f}% of crashes on {pct_wet_days:.0f}% of days -> CRI={cri_wet:.2f}")\n'
'print(f"Dry weather: {pct_dry_crashes:.1f}% of crashes on {pct_dry_days:.0f}% of days -> CRI={cri_dry:.2f}")'
))

cells.append(md("#### Level 3: Chi-Squared Test of Independence"))
cells.append(code(
'contingency = pd.crosstab(df[\'IS_WET_WEATHER\'], df[\'HAS_INJURY\'])\n'
'chi2_weather, p_chi_weather, dof_w, _ = stats.chi2_contingency(contingency)\n'
'print(f"Chi-squared = {chi2_weather:,.1f}, df = {dof_w}, p = {p_chi_weather:.2e}")\n'
'ct_display = contingency.copy()\n'
'ct_display.index = [\'Dry\', \'Wet\']\n'
'ct_display.columns = [\'No Injury\', \'Injury\']\n'
'print(ct_display.to_string())'
))

cells.append(md("#### Level 4: Odds Ratio with 95% CI"))
cells.append(code(
'a = contingency.iloc[1, 1]  # Wet & Injury\n'
'b = contingency.iloc[1, 0]  # Wet & No Injury\n'
'c = contingency.iloc[0, 1]  # Dry & Injury\n'
'd = contingency.iloc[0, 0]  # Dry & No Injury\n'
'OR = (a * d) / (b * c)\n'
'log_OR = np.log(OR)\n'
'SE_log_OR = np.sqrt(1/a + 1/b + 1/c + 1/d)\n'
'CI_lower = np.exp(log_OR - 1.96 * SE_log_OR)\n'
'CI_upper = np.exp(log_OR + 1.96 * SE_log_OR)\n'
'print(f"Odds Ratio (Wet vs Dry -> Injury): {OR:.3f}")\n'
'print(f"95% CI: ({CI_lower:.3f}, {CI_upper:.3f})")'
))

cells.append(md("#### Level 5: Logistic Regression Controlling for Confounders"))
cells.append(code(
'lr_df = df[[\'HAS_INJURY\', \'IS_WET_WEATHER\', \'IS_DARK\', \'POSTED_SPEED_LIMIT\',\n'
'            \'CRASH_HOUR\', \'CRASH_DAY_OF_WEEK\']].dropna()\n'
'model = smf.logit(\'HAS_INJURY ~ IS_WET_WEATHER + IS_DARK + POSTED_SPEED_LIMIT + C(CRASH_HOUR) + C(CRASH_DAY_OF_WEEK)\',\n'
'                   data=lr_df)\n'
'result = model.fit(maxiter=200, method=\'lbfgs\', disp=False)\n'
'\n'
'key_vars = [\'IS_WET_WEATHER\', \'IS_DARK\', \'POSTED_SPEED_LIMIT\']\n'
'print(f"Model converged: {result.mle_retvals[\'converged\']}")\n'
'print(f"Pseudo R-squared: {result.prsquared:.4f}")\n'
'print(f"Observations: {int(result.nobs):,}")\n'
'\n'
'or_data = []\n'
'for var in key_vars:\n'
'    coef = result.params[var]\n'
'    ci = result.conf_int().loc[var]\n'
'    or_val = np.exp(coef)\n'
'    or_lower = np.exp(ci.iloc[0])\n'
'    or_upper = np.exp(ci.iloc[1])\n'
'    p = result.pvalues[var]\n'
'    print(f"  {var}: OR={or_val:.3f}, 95% CI=({or_lower:.3f}, {or_upper:.3f}), p={p:.2e}")\n'
'    or_data.append({\'Variable\': var, \'OR\': or_val, \'CI_lower\': or_lower, \'CI_upper\': or_upper, \'p\': p})\n'
'or_df = pd.DataFrame(or_data)'
))

cells.append(md("#### Level 6: Stratified Analysis (Robustness Check)"))
cells.append(code(
'print("STRATIFIED ANALYSIS BY LIGHTING CONDITION")\n'
'strata = df.groupby(\'LIGHTING_CONDITION\')\n'
'for name, group in strata:\n'
'    ct = pd.crosstab(group[\'IS_WET_WEATHER\'], group[\'HAS_INJURY\'])\n'
'    if ct.shape == (2, 2) and (ct > 0).all().all():\n'
'        a_s = ct.iloc[1, 1]; b_s = ct.iloc[1, 0]\n'
'        c_s = ct.iloc[0, 1]; d_s = ct.iloc[0, 0]\n'
'        or_s = (a_s * d_s) / (b_s * c_s)\n'
'        se_s = np.sqrt(1/a_s + 1/b_s + 1/c_s + 1/d_s)\n'
'        ci_l = np.exp(np.log(or_s) - 1.96 * se_s)\n'
'        ci_u = np.exp(np.log(or_s) + 1.96 * se_s)\n'
'        print(f"  {name:<30} N={len(group):<10,} OR={or_s:.3f} ({ci_l:.3f}, {ci_u:.3f})")'
))

# Phase 3c: Key Findings
cells.append(md("---\n### 3c: Key Findings\n#### Finding 1: Hit-and-Run Patterns"))
cells.append(code(
'hr = df[df[\'HIT_AND_RUN_I\'] == \'Y\']\n'
'non_hr = df[df[\'HIT_AND_RUN_I\'] == \'N\']\n'
'print(f"Total H&R: {len(hr):,} ({len(hr)/len(df)*100:.1f}%)")\n'
'print(f"H&R injury rate: {hr[\'HAS_INJURY\'].mean()*100:.1f}%")\n'
'print(f"Non-H&R injury rate: {non_hr[\'HAS_INJURY\'].mean()*100:.1f}%")\n'
'\n'
'hr_contingency = pd.crosstab(df[\'HIT_AND_RUN_I\'], df[\'HAS_INJURY\'])\n'
'chi2_hr, p_hr, _, _ = stats.chi2_contingency(hr_contingency)\n'
'print(f"Chi-squared: chi2={chi2_hr:,.1f}, p={p_hr:.2e}")\n'
'\n'
'hr_rate_hour = df.groupby(\'CRASH_HOUR\')[\'HIT_AND_RUN_I\'].apply(lambda x: (x == \'Y\').mean() * 100)\n'
'hr_rate_dow = df.groupby(\'DAY_NAME\')[\'HIT_AND_RUN_I\'].apply(lambda x: (x == \'Y\').mean() * 100)\n'
'print("\\nPeak H&R hours:")\n'
'for h, pct in hr_rate_hour.nlargest(5).items():\n'
'    print(f"  {int(h):02d}:00 - {pct:.1f}%")'
))

cells.append(md("#### Finding 2: Speed Limit & Crash Severity"))
cells.append(code(
'speed_order = [\'0-20 mph\', \'25-30 mph\', \'35-40 mph\', \'45+ mph\']\n'
'speed_stats = df[df[\'SPEED_CATEGORY\'] != \'Unknown\'].groupby(\'SPEED_CATEGORY\').agg(\n'
'    total_crashes=(\'HAS_INJURY\', \'count\'),\n'
'    injury_rate=(\'HAS_INJURY\', \'mean\'),\n'
'    fatality_rate=(\'HAS_FATAL\', \'mean\'),\n'
'    avg_injuries=(\'INJURIES_TOTAL\', \'mean\')\n'
').reindex(speed_order)\n'
'speed_stats[\'injury_rate_pct\'] = speed_stats[\'injury_rate\'] * 100\n'
'speed_stats[\'fatality_rate_per_1000\'] = speed_stats[\'fatality_rate\'] * 1000\n'
'print(speed_stats[[\'total_crashes\', \'injury_rate_pct\', \'fatality_rate_per_1000\']].to_string())\n'
'\n'
'valid = df[df[\'POSTED_SPEED_LIMIT\'].notna() & df[\'INJURIES_TOTAL\'].notna()]\n'
'rho, p_spearman = stats.spearmanr(valid[\'POSTED_SPEED_LIMIT\'], valid[\'INJURIES_TOTAL\'])\n'
'rpb, p_pb = stats.pointbiserialr(valid[\'HAS_FATAL\'], valid[\'POSTED_SPEED_LIMIT\'])\n'
'print(f"\\nSpearman (speed vs injuries): rho={rho:.3f}, p={p_spearman:.2e}")\n'
'print(f"Point-biserial (speed vs fatal): r={rpb:.3f}, p={p_pb:.2e}")'
))

cells.append(md("#### Finding 3: Most Dangerous Contributory Causes"))
cells.append(code(
'causes_df = df[~df[\'PRIM_CONTRIBUTORY_CAUSE\'].isin([\'UNABLE TO DETERMINE\', \'NOT APPLICABLE\'])].copy()\n'
'cause_stats = causes_df.groupby(\'PRIM_CONTRIBUTORY_CAUSE\').agg(\n'
'    total_crashes=(\'HAS_INJURY\', \'count\'),\n'
'    injury_rate=(\'HAS_INJURY\', \'mean\'),\n'
'    fatalities=(\'INJURIES_FATAL\', \'sum\')\n'
').reset_index()\n'
'cause_stats[\'danger_score\'] = cause_stats[\'total_crashes\'] * cause_stats[\'injury_rate\']\n'
'cause_stats = cause_stats.sort_values(\'danger_score\', ascending=False).head(15)\n'
'cause_stats[\'injury_rate_pct\'] = cause_stats[\'injury_rate\'] * 100\n'
'print(cause_stats[[\'PRIM_CONTRIBUTORY_CAUSE\', \'total_crashes\', \'injury_rate_pct\', \'danger_score\']].to_string(index=False))'
))

# Phase 3d: Hotspot
cells.append(md("---\n### 3d: Crash Hotspot Identification\n**Q4: What are the key crash areas, and what safety measures should be considered?**"))
cells.append(code(
'injury_crashes = df[(df[\'HAS_INJURY\'] == 1) &\n'
'                    df[\'LATITUDE\'].notna() & df[\'LONGITUDE\'].notna() &\n'
'                    df[\'LATITUDE\'].between(41.6, 42.1) &\n'
'                    df[\'LONGITUDE\'].between(-87.95, -87.5)].copy()\n'
'print(f"Injury crashes with valid coordinates: {len(injury_crashes):,}")\n'
'\n'
'if len(injury_crashes) > 100000:\n'
'    print("Subsampling to 100,000 for DBSCAN...")\n'
'    injury_sample = injury_crashes.sample(n=100000, random_state=42)\n'
'else:\n'
'    injury_sample = injury_crashes\n'
'\n'
'coords_rad = np.radians(injury_sample[[\'LATITUDE\', \'LONGITUDE\']].values)\n'
'print("Running DBSCAN (eps=500m, min_samples=50, haversine)...")\n'
'db = DBSCAN(eps=0.5/6371, min_samples=50, metric=\'haversine\', algorithm=\'ball_tree\')\n'
'injury_sample = injury_sample.copy()\n'
'injury_sample[\'cluster\'] = db.fit_predict(coords_rad)\n'
'\n'
'n_clusters = len(set(injury_sample[\'cluster\'])) - (1 if -1 in injury_sample[\'cluster\'] else 0)\n'
'n_noise = (injury_sample[\'cluster\'] == -1).sum()\n'
'print(f"Clusters found: {n_clusters}")\n'
'print(f"Noise points: {n_noise:,} ({n_noise/len(injury_sample)*100:.1f}%)")\n'
'\n'
'cluster_profiles = []\n'
'for cid in injury_sample[injury_sample[\'cluster\'] >= 0][\'cluster\'].value_counts().head(20).index:\n'
'    cluster = injury_sample[injury_sample[\'cluster\'] == cid]\n'
'    cluster_profiles.append({\n'
'        \'cluster_id\': cid, \'crash_count\': len(cluster),\n'
'        \'center_lat\': cluster[\'LATITUDE\'].mean(), \'center_lon\': cluster[\'LONGITUDE\'].mean(),\n'
'        \'total_injuries\': cluster[\'INJURIES_TOTAL\'].sum(),\n'
'        \'fatalities\': cluster[\'INJURIES_FATAL\'].sum(),\n'
'        \'top_cause\': cluster[\'PRIM_CONTRIBUTORY_CAUSE\'].mode().iloc[0],\n'
'        \'top_lighting\': cluster[\'LIGHTING_CONDITION\'].mode().iloc[0],\n'
'        \'mean_speed_limit\': cluster[\'POSTED_SPEED_LIMIT\'].mean(),\n'
'        \'top_street\': cluster[\'STREET_NAME\'].mode().iloc[0] if len(cluster[\'STREET_NAME\'].dropna()) > 0 else \'N/A\'\n'
'    })\n'
'hotspots_df = pd.DataFrame(cluster_profiles)\n'
'print("\\nTop Crash Hotspots:")\n'
'print(hotspots_df[[\'top_street\', \'crash_count\', \'total_injuries\', \'fatalities\']].to_string(index=False))'
))

# Phase 4: Visualizations
cells.append(md("---\n## Phase 4: Visualizations\n### Chart 2: Day \u00d7 Hour Crash Density Heatmap"))
cells.append(code(
'fig, ax = plt.subplots(figsize=(14, 6))\n'
'fig.patch.set_linewidth(0)\n'
'sns.heatmap(heatmap_data, cmap=\'YlOrRd\', annot=False, ax=ax,\n'
'            linewidths=0.5, linecolor=\'white\',\n'
'            cbar_kws={\'label\': \'Number of Crashes\'})\n'
'ax.set_title(\'Crash Density by Day of Week and Hour\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.94, \'Darker = more crashes. Rush hours and Friday afternoons are highest risk\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'ax.set_xlabel(\'Hour of Day\')\n'
'ax.set_ylabel(\'\')\n'
'hour_labels = [\'12am\', \'\', \'\', \'3am\', \'\', \'\', \'6am\', \'\', \'\', \'9am\', \'\', \'\',\n'
'               \'12pm\', \'\', \'\', \'3pm\', \'\', \'\', \'6pm\', \'\', \'\', \'9pm\', \'\', \'\']\n'
'ax.set_xticks(np.arange(24) + 0.5)\n'
'ax.set_xticklabels(hour_labels, fontsize=9)\n'
'peak_val = heatmap_data.max().max()\n'
'for day in heatmap_data.index:\n'
'    for hour in heatmap_data.columns:\n'
'        if heatmap_data.loc[day, hour] == peak_val:\n'
'            day_idx = list(heatmap_data.index).index(day)\n'
'            hour_idx = list(heatmap_data.columns).index(hour)\n'
'            rect = plt.Rectangle((hour_idx, day_idx), 1, 1, fill=False, edgecolor=\'red\', linewidth=3)\n'
'            ax.add_patch(rect)\n'
'            ax.annotate(f\'Peak: {day} {int(hour)}:00\',\n'
'                       xy=(hour_idx + 0.5, day_idx + 0.5),\n'
'                       xytext=(hour_idx + 3, max(0, day_idx - 1.5)),\n'
'                       fontsize=10, fontweight=\'bold\', color=\'red\',\n'
'                       arrowprops=dict(arrowstyle=\'->\', color=\'red\', lw=1.5))\n'
'            break\n'
'    else:\n'
'        continue\n'
'    break\n'
'plt.tight_layout(rect=[0, 0, 1, 0.93])\n'
'plt.savefig(f\'{OUTPUT_DIR}/02_dow_hour_heatmap.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 3: Average Monthly Crashes"))
cells.append(code(
'monthly_by_year = df.groupby([\'CRASH_YEAR\', \'CRASH_MONTH\']).size().reset_index(name=\'count\')\n'
'monthly_avg = monthly_by_year.groupby(\'CRASH_MONTH\')[\'count\'].agg([\'mean\', \'std\']).reset_index()\n'
'month_names = [calendar.month_abbr[int(m)] for m in monthly_avg[\'CRASH_MONTH\']]\n'
'fig, ax = plt.subplots(figsize=(12, 5))\n'
'fig.patch.set_linewidth(0)\n'
'bars = ax.bar(month_names, monthly_avg[\'mean\'], yerr=monthly_avg[\'std\'],\n'
'              capsize=4, color=\'#005B96\', alpha=0.85, edgecolor=\'white\')\n'
'ax.set_title(\'Average Monthly Crash Count (2016\\u20132023) with Year-to-Year Variation\',\n'
'             fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.93, \'October sees highest crash volume; summer months also elevated\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'ax.set_ylabel(\'Crash Count\')\n'
'ax.set_xlabel(\'Month\')\n'
'ax.yaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\'{x:,.0f}\'))\n'
'peak_idx = monthly_avg[\'mean\'].idxmax()\n'
'bars[peak_idx].set_color(\'#E63946\')\n'
'for i, (val, std_val) in enumerate(zip(monthly_avg[\'mean\'], monthly_avg[\'std\'])):\n'
'    ax.text(i, val + std_val + 100, f\'{val:,.0f}\', ha=\'center\', va=\'bottom\', fontsize=8, fontweight=\'bold\')\n'
'ax.annotate(\'Peak: October\', xy=(peak_idx, monthly_avg[\'mean\'].iloc[peak_idx]),\n'
'           xytext=(peak_idx - 3, monthly_avg[\'mean\'].iloc[peak_idx] + monthly_avg[\'std\'].iloc[peak_idx] + 600),\n'
'           fontsize=10, fontweight=\'bold\', color=\'#E63946\',\n'
'           arrowprops=dict(arrowstyle=\'->\', color=\'#E63946\', lw=1.5))\n'
'ax.text(0.98, 0.02, \'Error bars = year-to-year standard deviation\',\n'
'        transform=ax.transAxes, ha=\'right\', va=\'bottom\', fontsize=8, color=\'gray\', style=\'italic\')\n'
'plt.tight_layout(rect=[0, 0, 1, 0.92])\n'
'plt.savefig(f\'{OUTPUT_DIR}/03_monthly_bar.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 4: Weather Condition Impact"))
cells.append(code(
'weather_plot = df[~df[\'WEATHER_CONDITION\'].isin([\'UNKNOWN\', \'OTHER\'])].groupby(\'WEATHER_CONDITION\').agg(\n'
'    total_crashes=(\'HAS_INJURY\', \'count\'), injury_rate=(\'HAS_INJURY\', \'mean\')\n'
').sort_values(\'total_crashes\', ascending=True)\n'
'weather_plot[\'injury_rate_pct\'] = weather_plot[\'injury_rate\'] * 100\n'
'fig, ax = plt.subplots(figsize=(12, 6))\n'
'fig.patch.set_linewidth(0)\n'
'y_pos = range(len(weather_plot))\n'
'ax.barh(y_pos, weather_plot[\'total_crashes\'], color=\'#005B96\', alpha=0.8, edgecolor=\'white\')\n'
'ax.set_yticks(y_pos)\n'
'ax.set_yticklabels(weather_plot.index, fontsize=10)\n'
'ax.set_xlabel(\'Total Crashes\')\n'
'ax.set_title(\'Crash Count and Injury Rate by Weather Condition\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.94, \'Rain and freezing conditions show elevated injury rates despite lower crash volumes\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\'{x:,.0f}\'))\n'
'ax.yaxis.grid(False)\n'
'ax.xaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'max_crashes_w = weather_plot[\'total_crashes\'].max()\n'
'for i, (crashes, inj_rate) in enumerate(zip(weather_plot[\'total_crashes\'], weather_plot[\'injury_rate_pct\'])):\n'
'    if crashes > max_crashes_w * 0.15:\n'
'        ax.text(crashes * 0.5, i, f\'{crashes:,.0f}\', ha=\'center\', va=\'center\', fontsize=9, fontweight=\'bold\', color=\'white\')\n'
'        rate_x = crashes + max_crashes_w * 0.02\n'
'    else:\n'
'        ax.text(crashes + max_crashes_w * 0.01, i, f\'{crashes:,.0f}\', ha=\'left\', va=\'center\', fontsize=8, color=\'#333333\')\n'
'        rate_x = crashes + max_crashes_w * 0.08\n'
'    ax.text(rate_x, i + 0.25, f\'\\u2191 {inj_rate:.1f}% injury rate\',\n'
'            ha=\'left\', va=\'center\', fontsize=8, color=\'#E63946\', fontweight=\'bold\')\n'
'ax.set_xlim(0, max_crashes_w * 1.25)\n'
'fig.text(0.5, -0.02, \'Note: CLEAR weather dominates because it is the most common condition.\',\n'
'         ha=\'center\', fontsize=8, color=\'gray\', style=\'italic\')\n'
'plt.tight_layout(rect=[0, 0.03, 1, 0.93])\n'
'plt.savefig(f\'{OUTPUT_DIR}/04_weather_impact.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 5: How Much Does Each Factor Increase Injury Risk?\n\nLogistic regression results translated into plain % increase. Bars = effect size, horizontal lines = 95% confidence range."))
cells.append(code(
'nobs = int(result.nobs)\n'
'r2 = result.prsquared\n'
'or_df_plot = or_df.copy()\n'
'or_df_plot[\'pct_increase\'] = (or_df_plot[\'OR\'] - 1) * 100\n'
'or_df_plot[\'ci_lo_pct\'] = (or_df_plot[\'CI_lower\'] - 1) * 100\n'
'or_df_plot[\'ci_hi_pct\'] = (or_df_plot[\'CI_upper\'] - 1) * 100\n'
'readable_labels = {\'IS_WET_WEATHER\': \'Wet Weather\\n(rain, snow, ice)\',\n'
'                   \'IS_DARK\': \'Darkness\\n(no daylight)\',\n'
'                   \'POSTED_SPEED_LIMIT\': \'Speed Limit\\n(each +1 mph)\'}\n'
'or_df_plot[\'label\'] = or_df_plot[\'Variable\'].map(readable_labels)\n'
'\n'
'fig, ax = plt.subplots(figsize=(10, 5))\n'
'fig.patch.set_linewidth(0)\n'
'y_pos5 = list(range(len(or_df_plot)))\n'
'bar_colors5 = [\'#E63946\' if pct > 10 else \'#F4A261\' if pct > 5 else \'#457B9D\'\n'
'               for pct in or_df_plot[\'pct_increase\']]\n'
'ax.barh(y_pos5, or_df_plot[\'pct_increase\'].values, color=bar_colors5, alpha=0.85,\n'
'        edgecolor=\'white\', height=0.55)\n'
'for i, (_, row) in enumerate(or_df_plot.iterrows()):\n'
'    ax.plot([row[\'ci_lo_pct\'], row[\'ci_hi_pct\']], [i, i], color=\'#333\', linewidth=2, solid_capstyle=\'round\')\n'
'    ax.plot([row[\'ci_lo_pct\'], row[\'ci_lo_pct\']], [i-0.1, i+0.1], color=\'#333\', linewidth=1.5)\n'
'    ax.plot([row[\'ci_hi_pct\'], row[\'ci_hi_pct\']], [i-0.1, i+0.1], color=\'#333\', linewidth=1.5)\n'
'for i, (_, row) in enumerate(or_df_plot.iterrows()):\n'
'    pct = row[\'pct_increase\']\n'
'    ax.text(row[\'ci_hi_pct\'] + 0.5, i,\n'
'            f\'+{pct:.1f}%  (range: {row[\"ci_lo_pct\"]:.1f}\\u2013{row[\"ci_hi_pct\"]:.1f}%)\',\n'
'            ha=\'left\', va=\'center\', fontsize=10, fontweight=\'bold\', color=\'#333\')\n'
'ax.set_yticks(y_pos5)\n'
'ax.set_yticklabels(or_df_plot[\'label\'].values, fontsize=11)\n'
'ax.set_xlabel(\'% Increase in Injury Risk (controlling for other factors)\', fontsize=11)\n'
'ax.axvline(x=0, color=\'gray\', linestyle=\'-\', linewidth=0.8, alpha=0.5)\n'
'ax.yaxis.grid(False)\n'
'ax.xaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\'+{x:.0f}%\' if x > 0 else f\'{x:.0f}%\'))\n'
'ax.set_title(\'How Much Does Each Factor Increase Injury Risk?\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.93,\n'
'         f\'Logistic regression controlling for all factors simultaneously  |  \'\n'
'         f\'n = {nobs:,}  |  All p < 0.001  |  Horizontal lines = 95% confidence range\',\n'
'         ha=\'center\', fontsize=9, color=\'gray\', style=\'italic\')\n'
'xmax5 = or_df_plot[\'ci_hi_pct\'].max()\n'
'ax.set_xlim(-1, xmax5 + 14)\n'
'plt.tight_layout(rect=[0, 0, 1, 0.92])\n'
'plt.savefig(f\'{OUTPUT_DIR}/05_forest_plot.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 6: Hit-and-Run Temporal Patterns"))
cells.append(code(
'fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n'
'fig.patch.set_linewidth(0)\n'
'overall_hr_rate = (df[\'HIT_AND_RUN_I\'] == \'Y\').mean() * 100\n'
'ax1.plot(hr_rate_hour.index, hr_rate_hour.values, \'o-\', color=\'#E63946\', linewidth=2, markersize=5)\n'
'ax1.fill_between(hr_rate_hour.index, hr_rate_hour.values, alpha=0.2, color=\'#E63946\')\n'
'ax1.axhline(y=overall_hr_rate, color=\'gray\', linestyle=\'--\', linewidth=1, alpha=0.7)\n'
'ax1.text(23, overall_hr_rate + 0.5, f\'Overall avg: {overall_hr_rate:.1f}%\', ha=\'right\', fontsize=8, color=\'gray\')\n'
'ax1.set_xlabel(\'Hour of Day\')\n'
'ax1.set_ylabel(\'Hit-and-Run Rate (%)\')\n'
'ax1.set_title(\'(a) Hit-and-Run Rate by Hour\', fontweight=\'bold\')\n'
'hour_ticks = list(range(0, 24, 3))\n'
'hour_tick_labels = [\'12am\', \'3am\', \'6am\', \'9am\', \'12pm\', \'3pm\', \'6pm\', \'9pm\']\n'
'ax1.set_xticks(hour_ticks)\n'
'ax1.set_xticklabels(hour_tick_labels, fontsize=9)\n'
'ax1.yaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'peak_hr_hour = hr_rate_hour.idxmax()\n'
'peak_hr_val = hr_rate_hour.max()\n'
'ax1.annotate(f\'Peak: {int(peak_hr_hour) % 12 or 12} {"AM" if peak_hr_hour < 12 else "PM"} ({peak_hr_val:.0f}%)\',\n'
'            xy=(peak_hr_hour, peak_hr_val),\n'
'            xytext=(peak_hr_hour + 4, peak_hr_val - 5),\n'
'            fontsize=9, fontweight=\'bold\', color=\'darkred\',\n'
'            arrowprops=dict(arrowstyle=\'->\', color=\'darkred\', lw=1.5))\n'
'hr_rate_dow_ordered = hr_rate_dow.reindex(day_order)\n'
'ax2.bar(range(7), hr_rate_dow_ordered.values, color=\'#E63946\', alpha=0.8, edgecolor=\'white\')\n'
'ax2.set_xticks(range(7))\n'
'ax2.set_xticklabels([d[:3] for d in day_order], fontsize=10)\n'
'ax2.set_ylabel(\'Hit-and-Run Rate (%)\')\n'
'ax2.set_title(\'(b) Hit-and-Run Rate by Day\', fontweight=\'bold\')\n'
'ax2.yaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'ax2.axhline(y=overall_hr_rate, color=\'gray\', linestyle=\'--\', linewidth=1, alpha=0.7)\n'
'for i, val in enumerate(hr_rate_dow_ordered.values):\n'
'    ax2.text(i, val + 0.2, f\'{val:.1f}%\', ha=\'center\', va=\'bottom\', fontsize=8, fontweight=\'bold\')\n'
'fig.suptitle(\'Hit-and-Run Crash Patterns\', fontsize=14, fontweight=\'bold\', y=1.02)\n'
'fig.text(0.5, 0.98, \'Late-night hours (midnight\\u20134 AM) have nearly 50% hit-and-run rate \\u2014 suggesting impaired driving\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'plt.tight_layout()\n'
'plt.savefig(f\'{OUTPUT_DIR}/06_hit_and_run.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 7: Speed Limit vs Crash Severity"))
cells.append(code(
'fig, ax1 = plt.subplots(figsize=(10, 5))\n'
'fig.patch.set_linewidth(0)\n'
'x = np.arange(len(speed_order))\n'
'bars7 = ax1.bar(x, speed_stats[\'injury_rate_pct\'], width=0.5, color=\'#E63946\', alpha=0.85,\n'
'               edgecolor=\'white\', label=\'Injury Rate (%)\', zorder=3)\n'
'ax1.set_ylabel(\'Injury Rate (%)\', color=\'#E63946\', fontsize=12)\n'
'ax1.tick_params(axis=\'y\', labelcolor=\'#E63946\')\n'
'ax1.yaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'ax2 = ax1.twinx()\n'
'ax2.plot(x, speed_stats[\'fatality_rate_per_1000\'], \'s-\', color=\'#1D3557\',\n'
'         linewidth=2.5, markersize=10, markerfacecolor=\'white\', markeredgewidth=2,\n'
'         label=\'Fatality Rate (per 1,000)\', zorder=4)\n'
'ax2.set_ylabel(\'Fatality Rate (per 1,000 crashes)\', color=\'#1D3557\', fontsize=12)\n'
'ax2.tick_params(axis=\'y\', labelcolor=\'#1D3557\')\n'
'x_labels = [f\'{cat}\\n(n={int(speed_stats.loc[cat, "total_crashes"]):,})\' for cat in speed_order]\n'
'ax1.set_xticks(x)\n'
'ax1.set_xticklabels(x_labels, fontsize=10)\n'
'ax1.set_xlabel(\'Posted Speed Limit\')\n'
'ax1.set_title(\'Crash Severity by Posted Speed Limit\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.93, \'Higher speed limits are strongly associated with more severe crash outcomes\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'for i, (inj, fat) in enumerate(zip(speed_stats[\'injury_rate_pct\'], speed_stats[\'fatality_rate_per_1000\'])):\n'
'    ax1.text(i, inj + 0.5, f\'{inj:.1f}%\', ha=\'center\', fontsize=9, fontweight=\'bold\', color=\'#E63946\')\n'
'    ax2.text(i, fat + 0.15, f\'{fat:.1f}\', ha=\'center\', fontsize=9, fontweight=\'bold\', color=\'#1D3557\')\n'
'fat_min = speed_stats[\'fatality_rate_per_1000\'].iloc[0]\n'
'fat_max = speed_stats[\'fatality_rate_per_1000\'].iloc[-1]\n'
'multiplier = fat_max / fat_min if fat_min > 0 else 0\n'
'ax1.text(0.98, 0.02, f\'{multiplier:.1f}x increase in fatality rate\\nfrom lowest to highest speed zone\',\n'
'         transform=ax1.transAxes, ha=\'right\', va=\'bottom\', fontsize=9,\n'
'         fontweight=\'bold\', color=\'#1D3557\',\n'
'         bbox=dict(boxstyle=\'round,pad=0.3\', facecolor=\'lightyellow\', alpha=0.8))\n'
'lines1, labels1 = ax1.get_legend_handles_labels()\n'
'lines2, labels2 = ax2.get_legend_handles_labels()\n'
'ax1.legend(lines1 + lines2, labels1 + labels2, loc=\'upper left\')\n'
'plt.tight_layout(rect=[0, 0, 1, 0.92])\n'
'plt.savefig(f\'{OUTPUT_DIR}/07_speed_severity.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 8: Most Dangerous Contributory Causes"))
cells.append(code(
'fig, ax = plt.subplots(figsize=(13, 7))\n'
'fig.patch.set_linewidth(0)\n'
'cs = cause_stats.sort_values(\'danger_score\', ascending=True)\n'
'norm = plt.Normalize(cs[\'injury_rate_pct\'].min(), cs[\'injury_rate_pct\'].max())\n'
'colors_cs = plt.cm.RdYlGn_r(norm(cs[\'injury_rate_pct\'].values))\n'
'bars8 = ax.barh(range(len(cs)), cs[\'total_crashes\'], color=colors_cs, edgecolor=\'white\', height=0.7)\n'
'ax.set_yticks(range(len(cs)))\n'
'ax.set_yticklabels(cs[\'PRIM_CONTRIBUTORY_CAUSE\'].str.title().str[:60], fontsize=9)\n'
'ax.set_xlabel(\'Total Crashes\')\n'
'ax.set_title(\'Top 15 Contributory Causes by Danger Score\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.95, \'Ranked by Danger Score (Volume \\u00d7 Injury Rate). Color = injury rate.\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\'{x:,.0f}\'))\n'
'ax.yaxis.grid(False)\n'
'ax.xaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'max_crashes_c = cs[\'total_crashes\'].max()\n'
'for i, (crashes, inj_rate) in enumerate(zip(cs[\'total_crashes\'], cs[\'injury_rate_pct\'])):\n'
'    text_color = \'white\' if crashes > max_crashes_c * 0.3 else \'black\'\n'
'    ax.text(min(crashes * 0.5, crashes - max_crashes_c * 0.02), i, f\'{crashes:,.0f}\',\n'
'            ha=\'center\', va=\'center\', fontsize=8, fontweight=\'bold\', color=text_color)\n'
'    ax.text(crashes + max_crashes_c * 0.01, i, f\'{inj_rate:.1f}% injury\',\n'
'            va=\'center\', fontsize=8, color=\'gray\')\n'
'for j in range(max(0, len(cs) - 3), len(cs)):\n'
'    bars8[j].set_edgecolor(\'black\')\n'
'    bars8[j].set_linewidth(2)\n'
'sm_cmap = plt.cm.ScalarMappable(cmap=\'RdYlGn_r\', norm=norm)\n'
'sm_cmap.set_array([])\n'
'cbar = plt.colorbar(sm_cmap, ax=ax, shrink=0.6)\n'
'cbar.set_label(\'Injury Rate (%) \\u2014 Green: Lower, Red: Higher\', fontsize=9)\n'
'plt.tight_layout(rect=[0, 0, 1, 0.94])\n'
'plt.savefig(f\'{OUTPUT_DIR}/08_contributory_causes.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 9: Crash Density Map (Static)"))
cells.append(code(
'fig, ax = plt.subplots(figsize=(10, 12))\n'
'fig.patch.set_linewidth(0)\n'
'valid_coords = df[df[\'LATITUDE\'].notna() & df[\'LONGITUDE\'].notna() &\n'
'                  df[\'LATITUDE\'].between(41.64, 42.02) & df[\'LONGITUDE\'].between(-87.84, -87.52)]\n'
'sample = valid_coords.sample(n=min(50000, len(valid_coords)), random_state=42)\n'
'ax.scatter(sample[\'LONGITUDE\'], sample[\'LATITUDE\'], alpha=0.02, s=1, c=\'#005B96\')\n'
'ax.set_title(\'Chicago Crash Density with Identified Hotspots\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.97, \'DBSCAN clustering (500m radius, min 50 crashes). Red circles = injury hotspots\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'if len(hotspots_df) > 0:\n'
'    sizes = hotspots_df[\'crash_count\'] / hotspots_df[\'crash_count\'].max() * 300\n'
'    ax.scatter(hotspots_df[\'center_lon\'], hotspots_df[\'center_lat\'],\n'
'               s=sizes, c=\'red\', alpha=0.7, edgecolors=\'darkred\', linewidth=1.5,\n'
'               zorder=5, label=\'Crash Hotspots\')\n'
'    for idx, (i, row) in enumerate(hotspots_df.head(10).iterrows()):\n'
'        offset_x = 10 if idx % 2 == 0 else -15\n'
'        offset_y = 10 if idx % 3 == 0 else -10\n'
'        ax.annotate(f\"{idx+1}. {row[\'top_street\']}\",\n'
'                   (row[\'center_lon\'], row[\'center_lat\']),\n'
'                   fontsize=9, fontweight=\'bold\', color=\'darkred\',\n'
'                   xytext=(offset_x, offset_y), textcoords=\'offset points\',\n'
'                   bbox=dict(boxstyle=\'round,pad=0.2\', facecolor=\'white\', alpha=0.7, edgecolor=\'none\'))\n'
'geo_refs = [(-87.63, 41.882, \'Downtown\'), (-87.63, 41.76, \'South Side\'),\n'
'            (-87.75, 41.98, "O\'Hare Area"), (-87.72, 41.88, \'West Side\')]\n'
'for lon, lat, name in geo_refs:\n'
'    ax.text(lon, lat, name, fontsize=10, color=\'navy\', alpha=0.4, fontweight=\'bold\', ha=\'center\', style=\'italic\')\n'
'for s_val, s_label in [(50, \'Small cluster\'), (150, \'Medium cluster\'), (300, \'Large cluster\')]:\n'
'    ax.scatter([], [], s=s_val, c=\'red\', alpha=0.7, edgecolors=\'darkred\', label=s_label)\n'
'ax.text(0.02, 0.02, f\'Blue density = all crashes ({min(50000, len(valid_coords)):,} sample)\',\n'
'        transform=ax.transAxes, fontsize=9, color=\'#005B96\', style=\'italic\')\n'
'ax.set_xlim(-87.84, -87.52)\n'
'ax.set_ylim(41.64, 42.02)\n'
'ax.set_xlabel(\'Longitude\')\n'
'ax.set_ylabel(\'Latitude\')\n'
'ax.legend(loc=\'upper right\', fontsize=9)\n'
'ax.set_aspect(\'equal\')\n'
'plt.tight_layout(rect=[0, 0, 1, 0.96])\n'
'plt.savefig(f\'{OUTPUT_DIR}/09_crash_density_map.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Chart 10: Year-over-Year Crash Trend"))
cells.append(code(
'yearly = df.groupby(\'CRASH_YEAR\').agg(\n'
'    total_crashes=(\'HAS_INJURY\', \'count\'),\n'
'    injury_crashes=(\'HAS_INJURY\', \'sum\'),\n'
'    fatalities=(\'INJURIES_FATAL\', \'sum\')\n'
').reset_index()\n'
'fig, ax = plt.subplots(figsize=(10, 5))\n'
'fig.patch.set_linewidth(0)\n'
'ax.plot(yearly[\'CRASH_YEAR\'], yearly[\'total_crashes\'], \'o-\', color=\'#005B96\',\n'
'        linewidth=2.5, markersize=8, markerfacecolor=\'white\', markeredgewidth=2, label=\'Total Crashes\')\n'
'ax.plot(yearly[\'CRASH_YEAR\'], yearly[\'injury_crashes\'], \'s-\', color=\'#E63946\',\n'
'        linewidth=2, markersize=7, markerfacecolor=\'white\', markeredgewidth=2, label=\'Injury Crashes\')\n'
'ax.yaxis.grid(True, alpha=0.3, linestyle=\'--\')\n'
'ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\'{x:,.0f}\'))\n'
'ax.axvspan(2019.7, 2020.3, alpha=0.1, color=\'red\', zorder=0)\n'
'covid_idx = yearly[yearly[\'CRASH_YEAR\'] == 2020].index[0]\n'
'ax.annotate(\'COVID-19\\nLockdown\', xy=(2020, yearly.loc[covid_idx, \'total_crashes\']),\n'
'           xytext=(2020.8, yearly[\'total_crashes\'].max() * 0.85),\n'
'           fontsize=10, fontweight=\'bold\', color=\'red\',\n'
'           arrowprops=dict(arrowstyle=\'->\', color=\'red\', lw=1.5))\n'
'for _, row in yearly.iterrows():\n'
'    ax.text(row[\'CRASH_YEAR\'], row[\'total_crashes\'] + yearly[\'total_crashes\'].max() * 0.02,\n'
'            f\"{int(row[\'total_crashes\']):,}\", ha=\'center\', fontsize=8, color=\'#005B96\', fontweight=\'bold\')\n'
'for i in range(1, len(yearly)):\n'
'    prev_val = yearly.iloc[i-1][\'total_crashes\']\n'
'    curr_val = yearly.iloc[i][\'total_crashes\']\n'
'    pct_change = (curr_val - prev_val) / prev_val * 100\n'
'    mid_y = (prev_val + curr_val) / 2\n'
'    mid_x = yearly.iloc[i-1][\'CRASH_YEAR\'] + 0.5\n'
'    change_color = \'#E63946\' if pct_change < 0 else \'#2A9D8F\'\n'
'    ax.text(mid_x, mid_y, f\'{pct_change:+.0f}%\', fontsize=7, color=change_color,\n'
'            fontweight=\'bold\', ha=\'center\', va=\'center\',\n'
'            bbox=dict(boxstyle=\'round,pad=0.15\', facecolor=\'white\', alpha=0.8, edgecolor=\'none\'))\n'
'ax.set_xlabel(\'Year\')\n'
'ax.set_ylabel(\'Number of Crashes\')\n'
'ax.set_title(\'Year-over-Year Crash Trend (2016\\u20132023)\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.93, \'2020 crash reduction reflects COVID-19 lockdowns; recovery visible from 2021\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'ax.legend(loc=\'upper left\')\n'
'ax.set_xticks(yearly[\'CRASH_YEAR\'])\n'
'plt.tight_layout(rect=[0, 0, 1, 0.92])\n'
'plt.savefig(f\'{OUTPUT_DIR}/10_yearly_trend.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

cells.append(md("### Interactive Maps (Folium)\n\nFully annotated maps with legends, tooltips, popups, layer controls, and geographic context."))
cells.append(code(
'# --- Map 1: Crash Heatmap with Hotspot Clusters ---\n'
'print("Generating interactive crash heatmap...")\n'
'm1 = folium.Map(location=[41.88, -87.63], zoom_start=11, tiles=\'CartoDB positron\')\n'
'Fullscreen().add_to(m1)\n'
'MiniMap(toggle_display=True).add_to(m1)\n'
'MousePosition(position=\'bottomleft\', prefix=\'Coords:\').add_to(m1)\n'
'\n'
'# Title overlay\n'
'title_html = \'\'\'\n'
'<div style="position:fixed;top:10px;left:60px;z-index:9999;\n'
'     background:rgba(0,91,150,0.92);padding:12px 24px;border-radius:8px;\n'
'     box-shadow:0 2px 8px rgba(0,0,0,0.3);">\n'
'  <span style="color:white;font-size:18px;font-weight:bold;font-family:Calibri,sans-serif;">\n'
'    Chicago Crash Density Heatmap with Hotspot Clusters</span><br>\n'
'  <span style="color:#c8dcf0;font-size:12px;font-family:Calibri,sans-serif;">\n'
'    776K crashes (2016&ndash;2023) &bull; 50K sample shown &bull; Red circles = DBSCAN injury hotspots</span>\n'
'</div>\n'
'\'\'\'\n'
'm1.get_root().html.add_child(folium.Element(title_html))\n'
'\n'
'heat_sample = valid_coords.sample(n=min(50000, len(valid_coords)), random_state=42)\n'
'heat_data = heat_sample[[\'LATITUDE\', \'LONGITUDE\']].values.tolist()\n'
'\n'
'# Heatmap layer in its own feature group\n'
'fg_heat = folium.FeatureGroup(name=\'Crash Density Heatmap\', show=True)\n'
'HeatMap(heat_data, radius=8, blur=10, max_zoom=13, gradient={0.2:\'blue\',0.4:\'lime\',0.6:\'yellow\',0.8:\'orange\',1.0:\'red\'}).add_to(fg_heat)\n'
'fg_heat.add_to(m1)\n'
'\n'
'# Hotspot clusters in their own feature group\n'
'if len(hotspots_df) > 0:\n'
'    fg_hotspots = folium.FeatureGroup(name=\'Injury Hotspot Clusters (DBSCAN)\', show=True)\n'
'    for idx, (_, row) in enumerate(hotspots_df.head(10).iterrows()):\n'
'        radius_px = max(8, row[\'crash_count\'] / hotspots_df[\'crash_count\'].max() * 25)\n'
'        popup_html = (\n'
'            f"<div style=\'font-family:Calibri,sans-serif;min-width:200px;\'>" \n'
'            f"<b style=\'font-size:14px;color:#005B96;\'>Hotspot #{idx+1}: {row[\'top_street\']}</b><br><hr>"\n'
'            f"<b>Crashes:</b> {int(row[\'crash_count\']):,}<br>"\n'
'            f"<b>Injuries:</b> {int(row[\'total_injuries\']):,}<br>"\n'
'            f"<b>Fatalities:</b> {int(row[\'fatalities\'])}<br>"\n'
'            f"<b>Top cause:</b> {row[\'top_cause\']}<br>"\n'
'            f"<b>Avg speed limit:</b> {row[\'mean_speed_limit\']:.0f} mph<br>"\n'
'            f"<b>Lighting:</b> {row[\'top_lighting\']}</div>"\n'
'        )\n'
'        folium.CircleMarker(\n'
'            location=[row[\'center_lat\'], row[\'center_lon\']],\n'
'            radius=radius_px,\n'
'            color=\'red\', fill=True, fill_color=\'red\', fill_opacity=0.7, weight=2,\n'
'            popup=folium.Popup(popup_html, max_width=280),\n'
'            tooltip=f"#{idx+1} {row[\'top_street\']} ({int(row[\'crash_count\']):,} crashes)"\n'
'        ).add_to(fg_hotspots)\n'
'        folium.Marker(\n'
'            location=[row[\'center_lat\'], row[\'center_lon\']],\n'
'            icon=folium.DivIcon(html=f\'<div style="font-size:11px;font-weight:bold;color:darkred;text-shadow:1px 1px white;">{idx+1}</div>\',\n'
'                                icon_size=(20, 20), icon_anchor=(10, 10))\n'
'        ).add_to(fg_hotspots)\n'
'    fg_hotspots.add_to(m1)\n'
'\n'
'# Legend overlay\n'
'legend_html = \'\'\'\n'
'<div style="position:fixed;bottom:30px;right:10px;z-index:9999;\n'
'     background:white;padding:12px 16px;border-radius:6px;border:1px solid #ccc;\n'
'     box-shadow:0 2px 6px rgba(0,0,0,0.2);font-family:Calibri,sans-serif;font-size:12px;">\n'
'  <b style="font-size:13px;">Legend</b><br>\n'
'  <span style="display:inline-block;width:60px;height:10px;\n'
'        background:linear-gradient(to right,blue,lime,yellow,orange,red);\n'
'        border-radius:2px;vertical-align:middle;margin-right:5px;"></span>\n'
'  Crash density (low &rarr; high)<br>\n'
'  <span style="display:inline-block;width:14px;height:14px;border-radius:50%;\n'
'        background:red;border:2px solid darkred;vertical-align:middle;margin-right:5px;"></span>\n'
'  Injury hotspot cluster<br>\n'
'  <span style="color:gray;font-size:10px;margin-top:4px;display:block;">\n'
'    Click any red circle for full details</span>\n'
'</div>\n'
'\'\'\'\n'
'm1.get_root().html.add_child(folium.Element(legend_html))\n'
'folium.LayerControl(collapsed=False).add_to(m1)\n'
'm1.save(f\'{OUTPUT_DIR}/crash_heatmap.html\')\n'
'print("Saved: crash_heatmap.html")\n'
'm1'
))

cells.append(code(
'# --- Map 2: Fatal Crashes ---\n'
'fatal_crashes = df[(df[\'HAS_FATAL\'] == 1) & df[\'LATITUDE\'].notna() & df[\'LONGITUDE\'].notna()]\n'
'm2 = folium.Map(location=[41.88, -87.63], zoom_start=11, tiles=\'CartoDB positron\')\n'
'Fullscreen().add_to(m2)\n'
'MiniMap(toggle_display=True).add_to(m2)\n'
'MousePosition(position=\'bottomleft\', prefix=\'Coords:\').add_to(m2)\n'
'\n'
'# Title overlay\n'
'title2_html = f\'\'\'\n'
'<div style="position:fixed;top:10px;left:60px;z-index:9999;\n'
'     background:rgba(139,0,0,0.92);padding:12px 24px;border-radius:8px;\n'
'     box-shadow:0 2px 8px rgba(0,0,0,0.3);">\n'
'  <span style="color:white;font-size:18px;font-weight:bold;font-family:Calibri,sans-serif;">\n'
'    Fatal Crash Locations &mdash; Chicago (2016&ndash;2023)</span><br>\n'
'  <span style="color:#f0c0c0;font-size:12px;font-family:Calibri,sans-serif;">\n'
'    {len(fatal_crashes):,} fatal crashes plotted &bull; Click any marker for details</span>\n'
'</div>\n'
'\'\'\'\n'
'm2.get_root().html.add_child(folium.Element(title2_html))\n'
'\n'
'fg_all = folium.FeatureGroup(name=f\'All Fatal Crashes ({len(fatal_crashes):,})\', show=True)\n'
'for _, row in fatal_crashes.iterrows():\n'
'    crash_yr = int(row[\'CRASH_DATE\'].year) if hasattr(row[\'CRASH_DATE\'], \'year\') else \'N/A\'\n'
'    cause = row[\'PRIM_CONTRIBUTORY_CAUSE\'] if pd.notna(row[\'PRIM_CONTRIBUTORY_CAUSE\']) else \'Unknown\'\n'
'    speed = f"{int(row[\'POSTED_SPEED_LIMIT\'])} mph" if pd.notna(row[\'POSTED_SPEED_LIMIT\']) else \'N/A\'\n'
'    popup_html = (\n'
'        f"<div style=\'font-family:Calibri,sans-serif;min-width:220px;\'>"\n'
'        f"<b style=\'font-size:13px;color:darkred;\'>Fatal Crash</b><br><hr>"\n'
'        f"<b>Date:</b> {str(row[\'CRASH_DATE\'])[:10]}<br>"\n'
'        f"<b>Cause:</b> {cause[:50]}<br>"\n'
'        f"<b>Speed limit:</b> {speed}<br>"\n'
'        f"<b>Lighting:</b> {row[\'LIGHTING_CONDITION\'] if pd.notna(row[\'LIGHTING_CONDITION\']) else \'N/A\'}<br>"\n'
'        f"<b>Weather:</b> {row[\'WEATHER_CONDITION\'] if pd.notna(row[\'WEATHER_CONDITION\']) else \'N/A\'}</div>"\n'
'    )\n'
'    folium.CircleMarker(\n'
'        location=[row[\'LATITUDE\'], row[\'LONGITUDE\']],\n'
'        radius=5, color=\'darkred\', fill=True, fill_color=\'darkred\', fill_opacity=0.7, weight=1,\n'
'        popup=folium.Popup(popup_html, max_width=300),\n'
'        tooltip=f"Fatal: {str(row[\'CRASH_DATE\'])[:10]}"\n'
'    ).add_to(fg_all)\n'
'fg_all.add_to(m2)\n'
'\n'
'# Legend for fatal map\n'
'legend2_html = f\'\'\'\n'
'<div style="position:fixed;bottom:30px;right:10px;z-index:9999;\n'
'     background:white;padding:12px 16px;border-radius:6px;border:1px solid #ccc;\n'
'     box-shadow:0 2px 6px rgba(0,0,0,0.2);font-family:Calibri,sans-serif;font-size:12px;">\n'
'  <b style="font-size:13px;">Legend</b><br>\n'
'  <span style="display:inline-block;width:12px;height:12px;border-radius:50%;\n'
'        background:darkred;border:1px solid #600;vertical-align:middle;margin-right:5px;"></span>\n'
'  Fatal crash location<br>\n'
'  <span style="color:gray;font-size:11px;margin-top:4px;display:block;">\n'
'    Total: {len(fatal_crashes):,} fatalities (2016&ndash;2023)<br>\n'
'    Click any marker for date, cause &amp; conditions</span>\n'
'</div>\n'
'\'\'\'\n'
'm2.get_root().html.add_child(folium.Element(legend2_html))\n'
'folium.LayerControl(collapsed=False).add_to(m2)\n'
'm2.save(f\'{OUTPUT_DIR}/fatal_crashes_map.html\')\n'
'print(f"Saved: fatal_crashes_map.html ({len(fatal_crashes):,} fatal crashes)")\n'
'm2'
))

cells.append(md("### Chart 11: Static Fatal Crash Map\n\nFor PowerPoint embedding (since HTML maps cannot be embedded directly)."))
cells.append(code(
'fig, ax = plt.subplots(figsize=(10, 12))\n'
'fig.patch.set_linewidth(0)\n'
'ax.scatter(sample[\'LONGITUDE\'], sample[\'LATITUDE\'], alpha=0.015, s=0.5, c=\'#b0c4de\', zorder=1)\n'
'ax.scatter(fatal_crashes[\'LONGITUDE\'], fatal_crashes[\'LATITUDE\'],\n'
'           s=12, c=\'darkred\', alpha=0.6, edgecolors=\'red\', linewidth=0.3, zorder=3, label=f\'Fatal crashes ({len(fatal_crashes):,})\')\n'
'if len(hotspots_df) > 0:\n'
'    for idx, (_, row) in enumerate(hotspots_df.head(10).iterrows()):\n'
'        ax.plot(row[\'center_lon\'], row[\'center_lat\'], \'o\', color=\'none\',\n'
'                markeredgecolor=\'orange\', markersize=15, markeredgewidth=2, zorder=4)\n'
'for lon, lat, name in [(-87.63, 41.882, \'Downtown\'), (-87.63, 41.76, \'South Side\'),\n'
'                        (-87.75, 41.98, "O\'Hare Area"), (-87.72, 41.88, \'West Side\')]:\n'
'    ax.text(lon, lat, name, fontsize=10, color=\'navy\', alpha=0.4, fontweight=\'bold\', ha=\'center\', style=\'italic\')\n'
'ax.set_xlim(-87.84, -87.52)\n'
'ax.set_ylim(41.64, 42.02)\n'
'ax.set_xlabel(\'Longitude\')\n'
'ax.set_ylabel(\'Latitude\')\n'
'ax.set_title(\'Fatal Crash Locations — Chicago (2016–2023)\', fontsize=14, fontweight=\'bold\')\n'
'fig.text(0.5, 0.97, f\'{len(fatal_crashes):,} fatal crashes plotted. Orange rings = injury hotspot centres.\',\n'
'         ha=\'center\', fontsize=10, color=\'gray\', style=\'italic\')\n'
'ax.legend(loc=\'upper right\', fontsize=9)\n'
'ax.set_aspect(\'equal\')\n'
'plt.tight_layout(rect=[0, 0, 1, 0.96])\n'
'plt.savefig(f\'{OUTPUT_DIR}/11_fatal_crash_map.png\', bbox_inches=\'tight\')\n'
'plt.show()'
))

# Phase 5: PowerPoint
cells.append(md("---\n## Phase 5: PowerPoint Presentation\n\nThe PowerPoint was generated by `run_analysis.py` and saved to `output/Chicago_Traffic_Crash_Analysis.pptx` (24 slides with question-driven section headers, including static and interactive maps)."))
cells.append(code(
'# List all output files\n'
'print("Output files:")\n'
'for f in sorted(os.listdir(OUTPUT_DIR)):\n'
'    fpath = os.path.join(OUTPUT_DIR, f)\n'
'    size = os.path.getsize(fpath)\n'
'    print(f"  {f} ({size/1024:.0f} KB)")\n'
'\n'
'conn.close()\n'
'print("\\nAnalysis complete.")'
))

# Build notebook
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.14.0"
        }
    },
    "cells": cells
}

with open('traffic_crash_analysis.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Notebook written with {len(cells)} cells")
